nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://195.35.29.110:3000', 'https://gova-elite.vercel.app']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://195.35.29.110:3000', 'https://gova-elite.vercel.app']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
