version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
