name: Api platform CI

on:
  push:
    paths:
    - 'server/**'
    branches:
    - main
  pull_request:
    paths:
    - 'server/**'
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .env
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> server/.env
        echo "APP_ENV=${{ secrets.APP_ENV }}" >> server/.env

    - name: Docker Compose Install
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/docker-compose
        
    - name: Build the Docker Compose stack
      run: cd server && docker-compose up -d

    - name: Install dependencies
      run: cd server && composer update

    - name: Make migrations
      run: cd server && php bin/console make:migration

    - name: Run migrations
      run: cd server && php bin/console doctrine:migrations:migrate --no-interaction

    - name: Run tests
      run: cd server && php bin/phpunit
