name: React CI

on:
  push:
    paths:
    - 'client/**'
    branches:
    - main
  pull_request:
    paths:
    - 'client/**'
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: cd client && npm install

    - name: Install Snyk
      run: npm install -g snyk

    - name: Auth Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check for vulnerabilities
      run: cd client && snyk test --severity-threshold=high
